### ISSUE TITLE
Rollup marko.server is not a function

### ISSUE THREAD

**Issue by eduardoacskimlinks** [marko-js/rollup#37]
## Version: 3.3.1
```
"@marko/express": "2.1.0",
"@marko/rollup": "3.3.1",
"@rollup/plugin-commonjs": "25.0.0",
"@rollup/plugin-node-resolve": "15.0.2",
"express": "4.18.2",
"rollup": "3.22.0"
```

<img width="898" alt="Screenshot 2023-05-19 at 15 57 40" src="https://github.com/marko-js/rollup/assets/74052373/0615612b-5bb2-460a-9960-b9626b4f3d15">

### Details

```
import nodeResolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import marko from "@marko/rollup";

// `npm run build` -> `production` is true
// `npm run dev` -> `production` is false
// const production = !process.env.ROLLUP_WATCH;

export default {
	input: "src/index.js",
	output: {
		file: 'public/bundle.js',
		format: 'iife', // immediately-invoked function expression — suitable for <script> tags
		sourcemap: true
	},  
  plugins: [
    marko.server(),
    nodeResolve({ preferBuiltins: true }),
    commonjs({
      extensions: [".js", ".marko"]
    }),
  ]
};
```
Followed tutorial of Marko + Rollup

### Expected Behavior

To compile the template with express in the server side

### Actual Behavior

Crashing

**Comment by DylanPiercey** [comment]
FYI this is fixed in the latest @marko/rollup release and also the example has been updated (`npm init marko -- --template rollup-express`).

**Comment by eduardoacskimlinks** [comment]
@DylanPiercey Thanks for the quick response, but I may add that the issue isn't fixed, and I will add extra context to help find the problem.

I am doing a server-side rendering app to compare Handlebars with Marko, which uses `"type": "module"` for NodeJS `18.16.0`. Additionally, I created a public repository to demo the issue https://github.com/eduardoacskimlinks/ssr-express-with-marko.


``` --> package.json
{
  "type": "module",
  "name": "ssr-marko-express",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "dev": "rollup -c"
  },
  "devDependencies": {
    "@marko/express": "2.1.0",
    "@marko/rollup": "4.0.3",
    "@rollup/plugin-commonjs": "25.0.0",
    "@rollup/plugin-node-resolve": "15.0.2",
    "express": "4.18.2",
    "rollup": "3.22.0"
  }
}
```

When I ran the rollup in the issue description, the error display complained about missing `@marko/compiler`. Once installed then, it complains about `@marko/translator-default` and after this, complaints `Cannot find module 'marko/package.json'`

You can see this in the screenshots below.

<img width="1420" alt="Screenshot 2023-05-22 at 09 27 01" src="https://github.com/marko-js/rollup/assets/74052373/b90cc40c-4a10-4d71-ade0-f12a404d0d8e">

<img width="1338" alt="Screenshot 2023-05-22 at 09 27 52" src="https://github.com/marko-js/rollup/assets/74052373/d134de87-17e6-4e12-8bf1-db67edfc8557">

<img width="1317" alt="Screenshot 2023-05-22 at 09 39 18" src="https://github.com/marko-js/rollup/assets/74052373/2a2f1ade-f4f8-43e7-a1aa-59aeba718bb7">

**Comment by DylanPiercey** [comment]
@eduardoacskimlinks you should ensure you have `@marko/compiler` as a `devDependency` and `marko` as a regular `dependency`.

Adding those (and `@rollup/plugin-json`) to your reproduction causes the bundle to work.

However I would still recommend basing your config off of the rollup starter template https://github.com/marko-js/examples/tree/master/examples/rollup-express

**Comment by eduardoacskimlinks** [comment]
@DylanPiercey, thanks for your reply. The position of the package.json doesn't impact bundling from rollup, as the project doesn't aim to be a library. Could you expand more on why this is a factor in this case?

Regarding the second suggestion, I will give it a try, but this is actually moving us away from [@marko-js/rollup](https://github.com/marko-js/rollup#linked-config) setup described on the Would it be possible to share why this basic configuration doesn't work?

**Comment by DylanPiercey** [comment]
@eduardoacskimlinks it's not about the position of the package.json, it's that @marko/rollup has a peerDependency on `@marko/compiler` (meaning you have to install that yourself) and `@marko/compiler` does not come with the runtime (the `marko` package) so you need to install that also.

you just need to `npm i marko @marko/compiler`.
